### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by jacereda** [fable-compiler/fable-graphics#17]
First attempt: `build.sh` in project root:

```
  1) Building /Users/jacereda/src/fsharp/fable-graphics/bindings/Fable.Graphics.fsproj failed with exitcode 1.
  2) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4155,41): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
  3) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4466,44): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
  4) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4466,74): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
  5) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4493,121): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
  6) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4494,105): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
  7) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4495,72): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
  8) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4496,103): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
  9) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4497,92): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 10) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4500,89): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 11) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4501,122): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 12) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4502,43): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 13) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4502,106): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 14) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4508,87): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 15) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4510,100): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 16) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4525,90): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 17) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4527,46): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 18) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4533,105): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 19) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4534,65): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 20) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4535,124): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 21) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4536,64): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 22) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4537,62): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 23) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4547,55): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 24) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4619,44): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 25) FS0039: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(4619,82): The namespace or module 'p2' is not defined. Maybe you want one of the following:   P2
 26) FS0501: /Users/jacereda/src/fsharp/fable-graphics/bindings/fable-import-phaser/Fable.Import.Phaser.fs(372,9): The object constructor 'Sprite' takes 5 argument(s) but is here given 0. The required signature is 'new : game:Phaser.Game * x:float * y:float * ?key:U4<string,Phaser.RenderTexture,Phaser.BitmapData,PIXI.Texture> * ?frame:U2<string,float> -> Phaser.Sprite'.
```

Second attempt, in `samples/pixi/basic` after running `npm update` in `samples`:

```
Jorges-MacBook-Pro:basic jacereda$ npm run build

> fable-pixi-samples@0.0.1 build /Users/jacereda/src/fsharp/fable-graphics/samples/pixi/basic
> node ../../node_modules/fable-compiler

fable-compiler 0.7.51: Start compilation...
Compiled basic/basic.js at 14:54:38
Bundling...
Bundled public/bundle.js at 14:54:41
Jorges-MacBook-Pro:basic jacereda$ npm start

> fable-pixi-samples@0.0.1 start /Users/jacereda/src/fsharp/fable-graphics/samples/pixi/basic
> node ../../server

module.js:529
    throw err;
    ^

Error: Cannot find module 'fable-core'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jacereda/src/fsharp/fable-graphics/samples/server/index.js:28:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fable-pixi-samples@0.0.1 start: `node ../../server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fable-pixi-samples@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jacereda/.npm/_logs/2018-01-11T13_55_15_353Z-debug.log
Jorges-MacBook-Pro:basic jacereda$ 
```

What am I doing wrong?

**Comment by MangelMaxime** [comment]
This repo is more or less dead.

If you are interested on Pixi samples here is the new repo: https://github.com/fable-compiler/samples-pixi

Also, now the bindings are under https://github.com/fable-compiler/fable-import

**Comment by jacereda** [comment]
Will try that one, thanks.
